
srcfiles_unittest = files(
    'http/crow_getroutes_test.cpp',
    'http/http2_connection_test.cpp',
    'http/http_body_test.cpp',
    'http/http_connection_test.cpp',
    'http/http_response_test.cpp',
    'redfish-core/include/dbus_log_watcher_test.cpp',
    'redfish-core/include/event_log_test.cpp',
    'redfish-core/include/event_matches_filter_test.cpp',
    'redfish-core/include/filter_expr_executor_test.cpp',
    'redfish-core/include/filter_expr_parser_test.cpp',
    'redfish-core/include/privileges_test.cpp',
    'redfish-core/include/redfish_aggregator_test.cpp',
    'redfish-core/include/redfish_oem_routing_test.cpp',
    'redfish-core/include/redfish_test.cpp',
) + test_sources

if (get_option('audit-events').allowed())
    srcfiles_unittest += files('include/audit_events_test.cpp')
endif

if (get_option('tests').allowed())
    gtest = dependency(
        'gtest_main',
        main: true,
        version: '>=1.15.0',
        required: true,
    )
    gmock = dependency('gmock', required: true)
    gtestlib = static_library('gtestlib', dependencies: [gtest, gmock])
    gtestdep = declare_dependency(
        link_with: gtestlib,
        dependencies: [
            gtest.partial_dependency(includes: true),
            gmock.partial_dependency(includes: true),
        ],
    )
    # generate the test executable
    foreach test_src : srcfiles_unittest
        test_bin = executable(
            fs.stem(test_src),
            test_src,
            link_with: bmcweblib,
            include_directories: [incdir, include_directories('..')],
            install_dir: bindir,
            dependencies: bmcweb_dependencies + [gtestdep],
        )
        test(fs.stem(test_src), test_bin, protocol: 'gtest')
    endforeach
endif
